url: https://kaiovisk.github.io/

# Metadados do blog
title: "Kaio Roque"
email: kaioroque.dev@gmail.com 
description: "A Física e as ciências exatas sob um olhar humano; jamais tecnocrata."

# Equipe responsável pelo presente trabalho
people:
- name: Kaio Henrique Roque Silva
  pic: 1
  social: 
  - title: twitter 
    url: #
  - title: facebook 
    url: #
  - title: instagram 
    url: #

# Redes sociais úteis (ao acadêmico)
social: 
  - title: linkedin 
    url: https://linkedin.com/in/kaioroque
  - title: github
    url: https://github.com/kaiovisk 

# Configurações de build 
markdown: kramdown
permalink: pretty  
highlighter: rouge
